name: 'coverage'

on:
  push:
    branches:
      - main
      - uat
      - develop
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable --check-cache || yarn install --force 

      - name: Genera client API
        run: yarn generate

      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@35fca4fae11c4934c4c8a561269dd09700410770 # v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn test:coverage
          threshold: 90
          annotations: none
          package-manager: yarn

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ vars.SONARCLOUD_ORG }}
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT_KEY }}
            -Dsonar.projectName="${{ vars.SONARCLOUD_PROJECT_NAME }}"
